"""Real-time IQ viewer for two independent nRF52833 receiver nodes.

Each receiver sends one UART frame containing IQ samples captured from one TX1
packet and one TX2 packet.  Frames from the two receivers are paired using the
(TX1 sequence number, TX2 sequence number) tuple before they are displayed.
"""

from __future__ import annotations

import queue
import struct
import threading
import time
from collections import deque
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import serial


# Serial configuration
SERIAL_PORT_1 = "COM28"
SERIAL_PORT_2 = "COM29"
BAUD_RATE = 115200
SERIAL_TIMEOUT_S = 0.2

# UART frame generated by projects/nrf52833/multi_rx1/multi_rx1.c
NUM_SAMPLES = 88
BYTES_PER_IQ = 4                       # int16 Q + int16 I
IQ_BYTES_PER_PACKET = NUM_SAMPLES * BYTES_PER_IQ
TOTAL_IQ_BYTES = IQ_BYTES_PER_PACKET * 2
FRAME_TERMINATOR = b"\xff\xff\xff"
FRAME_LENGTH = TOTAL_IQ_BYTES + 4 + 2 + len(FRAME_TERMINATOR)  # 713

# Geometry used by the optional TX2 angle estimate shown in the window title.
SPEED_OF_LIGHT = 299_792_458.0
SIGNAL_FREQUENCY_HZ = 2.402e9
RX_SPACING_M = 0.0625
FIRST_TX_ANGLE_DEG = 0.0
TIMER_TICKS_PER_US = 16.0
STATUS_PERIOD_S = 2.0
PLOT_HISTORY_LENGTH = 50

# Parameters used by the offline antenna-array post-processing script.
# REFERENCE_POSITION_DEG is the same "ref_position" passed to
# compensate_phase_offset() in antenna_array_visualization.py.
REFERENCE_POSITION_DEG = 0.0
# The real angle is not known during live capture.  It is stored in the same
# field used by the offline .npz files so antenna_array_visualization.load_data()
# can read realtime files without a format conversion step.
RECORDED_ANGLE_DEG = np.nan


def terminal_timestamp() -> str:
    """Return a terminal-friendly timestamp with millisecond resolution."""
    wall_time = time.time()
    milliseconds = int((wall_time % 1.0) * 1000.0)
    return f"{time.strftime('%H:%M:%S', time.localtime(wall_time))}.{milliseconds:03d}"


def decode_iq(data: bytes) -> tuple[np.ndarray, np.ndarray]:
    """Decode 88 samples stored as big-endian [Q:int16, I:int16]."""
    if len(data) != IQ_BYTES_PER_PACKET:
        raise ValueError(f"IQ block length {len(data)} != {IQ_BYTES_PER_PACKET}")

    words = np.frombuffer(data, dtype=">i2").reshape(NUM_SAMPLES, 2)
    q_data = words[:, 0].astype(np.float32)
    i_data = words[:, 1].astype(np.float32)
    return i_data, q_data


def decode_frame(frame: bytes) -> dict:
    """Decode one 713-byte UART frame from an RX node."""
    if len(frame) != FRAME_LENGTH:
        raise ValueError(f"frame length {len(frame)} != {FRAME_LENGTH}")
    if not frame.endswith(FRAME_TERMINATOR):
        raise ValueError("invalid frame terminator")

    tx1_i, tx1_q = decode_iq(frame[:IQ_BYTES_PER_PACKET])
    tx2_i, tx2_q = decode_iq(
        frame[IQ_BYTES_PER_PACKET:TOTAL_IQ_BYTES]
    )

    return {
        "interval": struct.unpack_from(">I", frame, TOTAL_IQ_BYTES)[0],
        "tx1_sqn": frame[TOTAL_IQ_BYTES + 4],
        "tx2_sqn": frame[TOTAL_IQ_BYTES + 5],
        "packet_1_I_data": tx1_i,
        "packet_1_Q_data": tx1_q,
        "packet_2_I_data": tx2_i,
        "packet_2_Q_data": tx2_q,
    }


def load_data(filename: str | Path) -> dict:
    """Load an offline/realtime .npz file using the antenna visualization format."""
    data = np.load(filename, allow_pickle=True)
    angle_list = data["angle_list"]
    num_triggers = int(data["num_triggers"])

    triggers = []
    for idx in range(num_triggers):
        prefix = f"trigger_{idx:03d}"
        trigger_data = {
            "index": idx,
            "angle": float(data[f"{prefix}_angle"]),
            "rx1_data": {
                "interval": int(data[f"{prefix}_rx1_interval"]),
                "tx1_sqn": int(data[f"{prefix}_rx1_tx1_sqn"]),
                "tx2_sqn": int(data[f"{prefix}_rx1_tx2_sqn"]),
                "packet_1_I_data": data[f"{prefix}_rx1_pkt1_I"],
                "packet_1_Q_data": data[f"{prefix}_rx1_pkt1_Q"],
                "packet_2_I_data": data[f"{prefix}_rx1_pkt2_I"],
                "packet_2_Q_data": data[f"{prefix}_rx1_pkt2_Q"],
            },
            "rx2_data": {
                "interval": int(data[f"{prefix}_rx2_interval"]),
                "tx1_sqn": int(data[f"{prefix}_rx2_tx1_sqn"]),
                "tx2_sqn": int(data[f"{prefix}_rx2_tx2_sqn"]),
                "packet_1_I_data": data[f"{prefix}_rx2_pkt1_I"],
                "packet_1_Q_data": data[f"{prefix}_rx2_pkt1_Q"],
                "packet_2_I_data": data[f"{prefix}_rx2_pkt2_I"],
                "packet_2_Q_data": data[f"{prefix}_rx2_pkt2_Q"],
            },
        }
        triggers.append(trigger_data)

    return {
        "angle_list": angle_list,
        "num_triggers": num_triggers,
        "triggers": triggers,
    }


def make_trigger_data(
    rx1: dict,
    rx2: dict,
    index: int,
    angle: float = RECORDED_ANGLE_DEG,
) -> dict:
    """Create the same trigger dictionary used by antenna_array_visualization.py."""
    return {
        "index": index,
        "angle": float(angle),
        "rx1_data": rx1,
        "rx2_data": rx2,
    }


def show_slotframe(trigger_data: dict, save_path: str | Path | None = None) -> None:
    """Visualize phase changes for one trigger using the offline script layout."""
    rx1_data = trigger_data["rx1_data"]
    rx2_data = trigger_data["rx2_data"]

    rx1_pkt1_phase = np.arctan2(
        rx1_data["packet_1_Q_data"], rx1_data["packet_1_I_data"]
    )
    rx1_pkt2_phase = np.arctan2(
        rx1_data["packet_2_Q_data"], rx1_data["packet_2_I_data"]
    )
    rx2_pkt1_phase = np.arctan2(
        rx2_data["packet_1_Q_data"], rx2_data["packet_1_I_data"]
    )
    rx2_pkt2_phase = np.arctan2(
        rx2_data["packet_2_Q_data"], rx2_data["packet_2_I_data"]
    )

    sample_indices = np.arange(len(rx1_pkt1_phase))
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    fig.suptitle(
        f"Phase Changes - Trigger {trigger_data['index']} "
        f"(Angle: {trigger_data['angle']:.2f} deg)",
        fontsize=14,
        fontweight="bold",
    )

    phase_plots = (
        (axes[0, 0], rx1_pkt1_phase, "b-o", "RX1 Packet 1 Phase", "RX1 Pkt1"),
        (axes[0, 1], rx1_pkt2_phase, "b-s", "RX1 Packet 2 Phase", "RX1 Pkt2"),
        (axes[1, 0], rx2_pkt1_phase, "g-o", "RX2 Packet 1 Phase", "RX2 Pkt1"),
        (axes[1, 1], rx2_pkt2_phase, "g-s", "RX2 Packet 2 Phase", "RX2 Pkt2"),
    )
    for axis, phase, style, title, label in phase_plots:
        axis.plot(sample_indices, phase, style, markersize=3, linewidth=1.5, label=label)
        axis.set_xlabel("Sample Index")
        axis.set_ylabel("Phase (rad)")
        axis.set_title(title)
        axis.grid(True, alpha=0.3)
        axis.legend()
        axis.set_ylim([-np.pi, np.pi])

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
    else:
        plt.show()


def calculate_angle(I1, Q1, I2, Q2):
    """Calculate wrapped phase difference between two IQ vectors."""
    phase1 = np.arctan2(np.asarray(Q1), np.asarray(I1))
    phase2 = np.arctan2(np.asarray(Q2), np.asarray(I2))
    theta = phase1 - phase2
    return np.arctan2(np.sin(theta), np.cos(theta))


def cal_slope(phase_diff):
    """Return linear slope/intercept of phase_diff versus sample index."""
    x = np.arange(len(phase_diff), dtype=np.float64)
    slope, intercept = np.polyfit(x, phase_diff, 1)
    return float(slope), float(intercept)


def phase_to_angle(geo):
    """Convert RX1/RX2 geometric phase difference to arrival angle."""
    val = geo / (2.0 * np.pi) * 12.5 / 4.3
    if val > 1:
        val = 1
    # Preserved from antenna_array_visualization.py for output compatibility.
    if val < -1:
        val = 1
    return np.arcsin(val) / np.pi * 180.0


def unwrap_and_adjust(numpy_array):
    unwrapped = np.unwrap(numpy_array)
    return np.arctan2(np.sin(unwrapped), np.cos(unwrapped))


def angle_to_phase(angle):
    """Convert reference angle to reference phase using the offline script formula."""
    return angle / 180.0 * np.pi * 4.3 / 12.5 * 2.0 * np.pi


def compensate_phase_offset(trigger_data: dict, ref_position: float) -> float:
    """Estimate TX2 angle with the same algorithm as antenna_array_visualization.py."""
    rx1_data = trigger_data["rx1_data"]
    rx2_data = trigger_data["rx2_data"]

    rx1_pkt1_phase = np.arctan2(
        rx1_data["packet_1_Q_data"], rx1_data["packet_1_I_data"]
    )
    rx1_pkt2_phase = np.arctan2(
        rx1_data["packet_2_Q_data"], rx1_data["packet_2_I_data"]
    )
    rx2_pkt1_phase = np.arctan2(
        rx2_data["packet_1_Q_data"], rx2_data["packet_1_I_data"]
    )
    rx2_pkt2_phase = np.arctan2(
        rx2_data["packet_2_Q_data"], rx2_data["packet_2_I_data"]
    )

    interval = (rx1_data["interval"] + rx2_data["interval"]) / 2.0
    pkt1_phase_diff_12 = calculate_angle(
        rx1_data["packet_1_I_data"],
        rx1_data["packet_1_Q_data"],
        rx2_data["packet_1_I_data"],
        rx2_data["packet_1_Q_data"],
    )
    pkt2_phase_diff_12 = calculate_angle(
        rx1_data["packet_2_I_data"],
        rx1_data["packet_2_Q_data"],
        rx2_data["packet_2_I_data"],
        rx2_data["packet_2_Q_data"],
    )

    pkt1_phase_diff_12 = np.unwrap(pkt1_phase_diff_12)
    pkt2_phase_diff_12 = np.unwrap(pkt2_phase_diff_12)
    slope_12, _ = cal_slope(pkt1_phase_diff_12)
    anchor_phase = angle_to_phase(ref_position)

    target_phase_diff_12 = np.arctan2(
        np.sin(
            pkt2_phase_diff_12
            - pkt1_phase_diff_12
            - slope_12 * interval / TIMER_TICKS_PER_US
            - anchor_phase
        ),
        np.cos(
            pkt2_phase_diff_12
            - pkt1_phase_diff_12
            - slope_12 * interval / TIMER_TICKS_PER_US
            - anchor_phase
        ),
    )
    target_phase_diff_12_unwrap = unwrap_and_adjust(target_phase_diff_12)
    phase_12 = float(np.mean(target_phase_diff_12_unwrap))

    # Keep these intermediate arrays because they are part of the original
    # offline function's ambiguity-resolution logic during development.
    _array1 = unwrap_and_adjust(rx1_pkt1_phase - rx1_pkt2_phase)
    _array2 = unwrap_and_adjust(rx2_pkt1_phase - rx2_pkt2_phase)
    _array12 = unwrap_and_adjust(_array1 - _array2)

    rx1_amplitude = float(
        np.mean(
            np.sqrt(
                rx1_data["packet_2_I_data"] ** 2 + rx1_data["packet_2_Q_data"] ** 2
            )
        )
    )
    rx2_amplitude = float(
        np.mean(
            np.sqrt(
                rx2_data["packet_2_I_data"] ** 2 + rx2_data["packet_2_Q_data"] ** 2
            )
        )
    )

    if rx1_amplitude < rx2_amplitude:
        if phase_12 > 0:
            return float(
                phase_to_angle(np.arctan2(np.sin(phase_12 - np.pi), np.cos(phase_12 - np.pi)))
            )
        return float(phase_to_angle(np.arctan2(np.sin(phase_12), np.cos(phase_12))))

    if phase_12 < 0:
        return float(
            phase_to_angle(np.arctan2(np.sin(phase_12 - np.pi), np.cos(phase_12 - np.pi)))
        )
    return float(phase_to_angle(np.arctan2(np.sin(phase_12), np.cos(phase_12))))


def filter_array(arr):
    """Remove saturated +/-90 degree estimates, matching the offline helper."""
    arr = np.array(arr)
    return arr[(arr != 90) & (arr != -90)]


class SerialFrameReader(threading.Thread):
    """Continuously receive and decode fixed-length UART frames."""

    def __init__(
        self,
        serial_port: serial.Serial,
        receiver_name: str,
        output_queue: queue.Queue,
        stop_event: threading.Event,
    ) -> None:
        super().__init__(daemon=True, name=f"reader-{receiver_name}")
        self.serial_port = serial_port
        self.receiver_name = receiver_name
        self.output_queue = output_queue
        self.stop_event = stop_event
        self.buffer = bytearray()
        self.bytes_received = 0
        self.frames_received = 0
        self.last_frame_time: float | None = None

    def _publish(self, frame: dict) -> None:
        self.frames_received += 1
        self.last_frame_time = time.monotonic()
        print(
            f"[{terminal_timestamp()}] {self.receiver_name} UART frame "
            f"#{self.frames_received}: TX1 seq={frame['tx1_sqn']}, "
            f"TX2 seq={frame['tx2_sqn']}, interval={frame['interval']} ticks",
            flush=True,
        )

        # Preserve recent data instead of blocking serial reception on a full UI queue.
        if self.output_queue.full():
            try:
                self.output_queue.get_nowait()
            except queue.Empty:
                pass
        self.output_queue.put_nowait(frame)

    def _extract_frames(self) -> None:
        # There is no start delimiter in the firmware frame.  Slide one byte at a
        # time until a 713-byte candidate ends in FF FF FF, then decode it.
        while len(self.buffer) >= FRAME_LENGTH:
            candidate = bytes(self.buffer[:FRAME_LENGTH])
            if candidate.endswith(FRAME_TERMINATOR):
                del self.buffer[:FRAME_LENGTH]
                try:
                    self._publish(decode_frame(candidate))
                except ValueError as error:
                    print(f"{self.receiver_name}: {error}")
            else:
                del self.buffer[0]

    def run(self) -> None:
        while not self.stop_event.is_set():
            try:
                waiting = self.serial_port.in_waiting
                chunk = self.serial_port.read(waiting if waiting else 1)
                if chunk:
                    self.bytes_received += len(chunk)
                    self.buffer.extend(chunk)
                    self._extract_frames()
            except serial.SerialException as error:
                print(f"{self.receiver_name} serial error: {error}")
                self.stop_event.set()
                return


def theoretical_phase(angle_deg: float) -> float:
    wavelength = SPEED_OF_LIGHT / SIGNAL_FREQUENCY_HZ
    phase = (
        2.0
        * np.pi
        * RX_SPACING_M
        * np.sin(np.deg2rad(angle_deg))
        / wavelength
    )
    return float(np.arctan2(np.sin(phase), np.cos(phase)))


def iq_phase(i_data: np.ndarray, q_data: np.ndarray) -> np.ndarray:
    return np.unwrap(np.arctan2(q_data, i_data))


def estimate_tx2_angle(rx1: dict, rx2: dict) -> float:
    """Use TX1 as phase/drift reference and estimate TX2 arrival angle."""
    rx1_tx1_phase = iq_phase(rx1["packet_1_I_data"], rx1["packet_1_Q_data"])
    rx2_tx1_phase = iq_phase(rx2["packet_1_I_data"], rx2["packet_1_Q_data"])
    rx1_tx2_phase = iq_phase(rx1["packet_2_I_data"], rx1["packet_2_Q_data"])
    rx2_tx2_phase = iq_phase(rx2["packet_2_I_data"], rx2["packet_2_Q_data"])

    tx1_difference = np.unwrap(rx1_tx1_phase - rx2_tx1_phase)
    sample_index = np.arange(NUM_SAMPLES, dtype=np.float64)
    slope, intercept = np.polyfit(sample_index, tx1_difference, 1)

    interval_ticks = (rx1["interval"] + rx2["interval"]) / 2.0
    interval_us = interval_ticks / TIMER_TICKS_PER_US
    hardware_phase_at_tx1 = intercept - theoretical_phase(FIRST_TX_ANGLE_DEG)
    predicted_hardware_phase = hardware_phase_at_tx1 + interval_us * slope

    tx2_difference = np.unwrap(rx1_tx2_phase - rx2_tx2_phase)
    geometric_phase = tx2_difference - predicted_hardware_phase
    geometric_phase = np.arctan2(np.sin(geometric_phase), np.cos(geometric_phase))
    mean_phase = float(np.mean(geometric_phase))

    wavelength = SPEED_OF_LIGHT / SIGNAL_FREQUENCY_HZ
    sine_value = mean_phase * wavelength / (2.0 * np.pi * RX_SPACING_M)
    return float(np.rad2deg(np.arcsin(np.clip(sine_value, -1.0, 1.0))))


def frame_key(frame: dict) -> tuple[int, int]:
    return frame["tx1_sqn"], frame["tx2_sqn"]


def take_matching_frames(
    rx1_buffer: deque,
    rx2_buffer: deque,
) -> tuple[dict, dict] | None:
    """Remove and return the newest sequence-matched frame pair."""
    rx2_indices = {frame_key(frame): index for index, frame in enumerate(rx2_buffer)}
    for rx1_index in range(len(rx1_buffer) - 1, -1, -1):
        key = frame_key(rx1_buffer[rx1_index])
        if key in rx2_indices:
            rx2_index = rx2_indices[key]
            rx1_frame = rx1_buffer[rx1_index]
            rx2_frame = rx2_buffer[rx2_index]
            del rx1_buffer[rx1_index]
            del rx2_buffer[rx2_index]
            return rx1_frame, rx2_frame
    return None


class RealtimeIQPlot:
    """Amplitude range and in-packet phase-slope history for matched packet pairs."""

    SIGNALS = (
        ("RX1 <- TX1", "rx1", "packet_1"),
        ("RX1 <- TX2", "rx1", "packet_2"),
        ("RX2 <- TX1", "rx2", "packet_1"),
        ("RX2 <- TX2", "rx2", "packet_2"),
    )

    def __init__(self) -> None:
        self.figure, self.axes = plt.subplots(
            4,
            2,
            figsize=(14, 10),
            sharex=True,
            constrained_layout=True,
        )
        self.figure.canvas.manager.set_window_title("Two-node real-time IQ viewer")
        self.update_count = 0
        self.last_update_time: float | None = None
        self.packet_indices: deque = deque(maxlen=PLOT_HISTORY_LENGTH)
        self.history = {
            name: {
                "amplitude": deque(maxlen=PLOT_HISTORY_LENGTH),
                "phase_slope": deque(maxlen=PLOT_HISTORY_LENGTH),
            }
            for name, _, _ in self.SIGNALS
        }
        # All four amplitude plots share this cumulative maximum.  It may grow
        # when a larger packet arrives, but never shrinks on later updates.
        self.amplitude_ymax = 1.0

        for row, (name, _, _) in enumerate(self.SIGNALS):
            self._configure_axes(row, name)

        self.figure.suptitle("Waiting for matched UART frames...")
        plt.show(block=False)

    @staticmethod
    def _amplitude_phase(frame: dict, packet_prefix: str) -> tuple[np.ndarray, np.ndarray]:
        i_data = frame[f"{packet_prefix}_I_data"]
        q_data = frame[f"{packet_prefix}_Q_data"]
        amplitude = np.hypot(i_data, q_data)
        # Unwrapped phase is used for slope fitting so +/-pi wrapping does not
        # create artificial jumps inside one 88-sample packet.
        phase_rad = np.unwrap(np.arctan2(q_data, i_data))
        return amplitude, phase_rad

    @staticmethod
    def _packet_summary(values: np.ndarray) -> tuple[float, float, float]:
        """Return minimum, mean, and maximum for one 88-sample packet."""
        return float(np.min(values)), float(np.mean(values)), float(np.max(values))

    @staticmethod
    def _phase_slope(phase_rad: np.ndarray) -> float:
        """Return the linear phase slope inside one packet, in rad/sample."""
        sample_index = np.arange(len(phase_rad), dtype=np.float64)
        slope, _ = np.polyfit(sample_index, phase_rad, 1)
        return float(slope)

    def _configure_axes(self, row: int, name: str) -> None:
        amplitude_axis = self.axes[row, 0]
        phase_axis = self.axes[row, 1]
        amplitude_axis.set_title(f"{name} amplitude range per packet")
        phase_axis.set_title(f"{name} in-packet phase slope")
        amplitude_axis.set_ylabel("Magnitude")
        phase_axis.set_ylabel("Slope (rad/sample)")
        amplitude_axis.set_ylim(0.0, self.amplitude_ymax)
        amplitude_axis.grid(True, alpha=0.3)
        phase_axis.grid(True, alpha=0.3)
        if row == len(self.SIGNALS) - 1:
            amplitude_axis.set_xlabel("Matched packet number")
            phase_axis.set_xlabel("Matched packet number")

    @staticmethod
    def _draw_i_history(axis, x_values: np.ndarray, summaries: deque, color: str) -> None:
        """Draw connected means with capped min/max bars (I-shaped glyphs)."""
        values = np.asarray(summaries, dtype=np.float64)
        minimum = values[:, 0]
        mean = values[:, 1]
        maximum = values[:, 2]
        y_error = np.vstack((mean - minimum, maximum - mean))
        axis.errorbar(
            x_values,
            mean,
            yerr=y_error,
            fmt="o-",
            color=color,
            ecolor=color,
            linewidth=1.0,
            elinewidth=1.2,
            capsize=5,
            capthick=1.2,
            markersize=3.5,
        )

    def update(self, rx1: dict, rx2: dict, match_count: int) -> float:
        frames = {"rx1": rx1, "rx2": rx2}
        self.packet_indices.append(match_count)

        for name, receiver_key, packet_prefix in self.SIGNALS:
            amplitude, phase = self._amplitude_phase(
                frames[receiver_key], packet_prefix
            )
            amplitude_summary = self._packet_summary(amplitude)
            phase_slope = self._phase_slope(phase)
            self.history[name]["amplitude"].append(amplitude_summary)
            self.history[name]["phase_slope"].append(phase_slope)
            self.amplitude_ymax = max(
                self.amplitude_ymax,
                amplitude_summary[2] * 1.05,
            )

        x_values = np.asarray(self.packet_indices)
        for row, (name, _, _) in enumerate(self.SIGNALS):
            amplitude_axis = self.axes[row, 0]
            phase_axis = self.axes[row, 1]
            amplitude_axis.clear()
            phase_axis.clear()
            self._configure_axes(row, name)
            self._draw_i_history(
                amplitude_axis,
                x_values,
                self.history[name]["amplitude"],
                "tab:blue",
            )
            phase_axis.plot(
                x_values,
                np.asarray(self.history[name]["phase_slope"], dtype=np.float64),
                "o-",
                color="tab:orange",
                linewidth=1.0,
                markersize=3.5,
            )
            phase_axis.axhline(0.0, color="black", linewidth=0.8, alpha=0.4)
            amplitude_axis.set_ylim(0.0, self.amplitude_ymax)

        trigger_data = make_trigger_data(rx1, rx2, match_count - 1)
        angle = compensate_phase_offset(trigger_data, REFERENCE_POSITION_DEG)
        self.update_count += 1
        self.last_update_time = time.monotonic()
        self.figure.suptitle(
            f"Matched pair #{match_count} | sequence={frame_key(rx1)} | "
            f"interval RX1={rx1['interval']} ticks, RX2={rx2['interval']} ticks | "
            f"TX2 angle={angle:.2f} degree"
        )
        self.figure.canvas.draw_idle()
        print(
            f"[{terminal_timestamp()}] PLOT UPDATED #{self.update_count}: "
            f"matched sequence={frame_key(rx1)}, TX2 angle={angle:.2f} degree",
            flush=True,
        )
        return angle

    def is_open(self) -> bool:
        return plt.fignum_exists(self.figure.number)


class RealtimeAnglePlot:
    """Real-time visualization of the compensated angle estimate."""

    def __init__(self) -> None:
        self.figure, self.axis = plt.subplots(figsize=(10, 4), constrained_layout=True)
        self.figure.canvas.manager.set_window_title("Real-time compensated angle")
        self.packet_indices: deque = deque(maxlen=PLOT_HISTORY_LENGTH)
        self.angles: deque = deque(maxlen=PLOT_HISTORY_LENGTH)
        self.update_count = 0
        self._configure_axis()
        # plt.show(block=False)

    def _configure_axis(self) -> None:
        self.axis.set_title(
            f"Estimated TX2 angle, reference={REFERENCE_POSITION_DEG:.1f} deg"
        )
        self.axis.set_xlabel("Matched packet number")
        self.axis.set_ylabel("Estimated angle (degree)")
        self.axis.set_ylim(-90.0, 90.0)
        self.axis.grid(True, alpha=0.3)

    def update(self, match_count: int, angle: float) -> None:
        self.packet_indices.append(match_count)
        self.angles.append(angle)
        self.update_count += 1

        x_values = np.asarray(self.packet_indices)
        y_values = np.asarray(self.angles)
        self.axis.clear()
        self._configure_axis()
        self.axis.plot(x_values, y_values, "o-", color="tab:red", linewidth=1.2)
        self.axis.axhline(0.0, color="black", linewidth=0.8, alpha=0.5)
        self.axis.text(
            0.02,
            0.92,
            f"latest={angle:.2f} deg",
            transform=self.axis.transAxes,
            fontsize=11,
            bbox={"facecolor": "white", "alpha": 0.75, "edgecolor": "none"},
        )
        self.figure.canvas.draw_idle()

    def is_open(self) -> bool:
        return plt.fignum_exists(self.figure.number)


def drain(source: queue.Queue, destination: deque) -> None:
    while True:
        try:
            destination.append(source.get_nowait())
        except queue.Empty:
            return


def age_text(event_time: float | None, now: float) -> str:
    if event_time is None:
        return "never"
    return f"{now - event_time:.1f}s ago"


def save_records(records: list[tuple[dict, dict]]) -> None:
    if not records:
        return

    output_directory = Path("discrete_antenna_experiment")
    output_directory.mkdir(parents=True, exist_ok=True)
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_path = output_directory / f"realtime_iq_{timestamp}.npz"

    save_data: dict[str, np.ndarray] = {
        "angle_list": np.array([RECORDED_ANGLE_DEG], dtype=np.float64),
        "num_triggers": np.array(len(records), dtype=np.int32),
    }

    for index, (rx1_frame, rx2_frame) in enumerate(records):
        trigger = make_trigger_data(rx1_frame, rx2_frame, index)
        prefix = f"trigger_{index:03d}"
        save_data[f"{prefix}_angle"] = np.array(trigger["angle"], dtype=np.float64)

        for receiver_name, receiver_data in (
            ("rx1", trigger["rx1_data"]),
            ("rx2", trigger["rx2_data"]),
        ):
            save_data[f"{prefix}_{receiver_name}_interval"] = np.array(
                receiver_data["interval"], dtype=np.uint32
            )
            save_data[f"{prefix}_{receiver_name}_tx1_sqn"] = np.array(
                receiver_data["tx1_sqn"], dtype=np.uint8
            )
            save_data[f"{prefix}_{receiver_name}_tx2_sqn"] = np.array(
                receiver_data["tx2_sqn"], dtype=np.uint8
            )
            save_data[f"{prefix}_{receiver_name}_pkt1_I"] = receiver_data[
                "packet_1_I_data"
            ]
            save_data[f"{prefix}_{receiver_name}_pkt1_Q"] = receiver_data[
                "packet_1_Q_data"
            ]
            save_data[f"{prefix}_{receiver_name}_pkt2_I"] = receiver_data[
                "packet_2_I_data"
            ]
            save_data[f"{prefix}_{receiver_name}_pkt2_Q"] = receiver_data[
                "packet_2_Q_data"
            ]

    np.savez(output_path, **save_data)
    print(
        f"Saved {len(records)} matched packet pairs to {output_path} "
        f"(antenna_array_visualization.py compatible)"
    )


def main() -> None:
    stop_event = threading.Event()
    rx1_queue: queue.Queue = queue.Queue(maxsize=20)
    rx2_queue: queue.Queue = queue.Queue(maxsize=20)
    rx1_buffer: deque = deque(maxlen=20)
    rx2_buffer: deque = deque(maxlen=20)
    records: list[tuple[dict, dict]] = []

    serial_1 = serial.Serial(SERIAL_PORT_1, BAUD_RATE, timeout=SERIAL_TIMEOUT_S)
    serial_2 = serial.Serial(SERIAL_PORT_2, BAUD_RATE, timeout=SERIAL_TIMEOUT_S)
    readers = (
        SerialFrameReader(serial_1, "RX1", rx1_queue, stop_event),
        SerialFrameReader(serial_2, "RX2", rx2_queue, stop_event),
    )
    for reader in readers:
        reader.start()

    viewer = RealtimeIQPlot()
    angle_viewer = RealtimeAnglePlot()
    match_count = 0
    last_status_time = time.monotonic()
    print(
        f"[{terminal_timestamp()}] Monitoring started: "
        f"RX1={SERIAL_PORT_1}, RX2={SERIAL_PORT_2}, frame length={FRAME_LENGTH}",
        flush=True,
    )
    try:
        while viewer.is_open() and angle_viewer.is_open() and not stop_event.is_set():
            drain(rx1_queue, rx1_buffer)
            drain(rx2_queue, rx2_buffer)

            match = take_matching_frames(rx1_buffer, rx2_buffer)
            while match is not None:
                rx1_frame, rx2_frame = match
                match_count += 1
                records.append((rx1_frame, rx2_frame))
                angle = viewer.update(rx1_frame, rx2_frame, match_count)
                angle_viewer.update(match_count, angle)
                match = take_matching_frames(rx1_buffer, rx2_buffer)

            now = time.monotonic()
            if now - last_status_time >= STATUS_PERIOD_S:
                plot_state = (
                    "UPDATING"
                    if viewer.last_update_time is not None
                    and now - viewer.last_update_time < STATUS_PERIOD_S * 1.5
                    else "WAITING FOR MATCH"
                )
                print(
                    f"[{terminal_timestamp()}] STATUS: "
                    f"RX1 bytes={readers[0].bytes_received}, "
                    f"frames={readers[0].frames_received} "
                    f"(last {age_text(readers[0].last_frame_time, now)}), "
                    f"RX2 bytes={readers[1].bytes_received}, "
                    f"frames={readers[1].frames_received} "
                    f"(last {age_text(readers[1].last_frame_time, now)}), "
                    f"matched={match_count}, plot={plot_state}, "
                    f"unmatched buffers=({len(rx1_buffer)}, {len(rx2_buffer)})",
                    flush=True,
                )
                last_status_time = now

            plt.pause(0.03)
    except KeyboardInterrupt:
        pass
    finally:
        stop_event.set()
        serial_1.close()
        serial_2.close()
        save_records(records)
        plt.close("all")


if __name__ == "__main__":
    main()
